-- CreateTable
CREATE TABLE `WISMA` (
    `WISMA_ID` VARCHAR(36) NOT NULL,
    `WISMA_NAMA` VARCHAR(200) NOT NULL,
    `WISMA_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `WISMA_UPDATED_AT` DATETIME(3) NULL,
    `WISMA_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`WISMA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
