-- CreateTable
CREATE TABLE `KOTA` (
    `KOTA_ID` VARCHAR(36) NOT NULL,
    `KOTA_NAMA` VARCHAR(200) NOT NULL,
    `KOTA_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `KOTA_UPDATED_AT` DATETIME(3) NULL,
    `KOTA_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`KOTA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
