-- AlterTable
ALTER TABLE `BIRO` MODIFY `BIRO_UPDATED_AT` DATETIME(3) NULL;

-- CreateTable
CREATE TABLE `PROVINSI` (
    `PROVINSI_ID` VARCHAR(36) NOT NULL,
    `PROVINSI_NAMA` VARCHAR(200) NOT NULL,
    `PROVINSI_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `PROVINSI_UPDATED_AT` DATETIME(3) NULL,
    `PROVINSI_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`PROVINSI_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
