-- AddForeignKey
ALTER TABLE `PROGRAM_STUDI` ADD CONSTRAINT `PROGRAM_STUDI_PRODI_FAKULTAS_fkey` FOREIGN KEY (`PRODI_FAKULTAS`) REFERENCES `FAKULTAS`(`FAKULTAS_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
