-- AddForeignKey
ALTER TABLE `SATUAN_KERJA` ADD CONSTRAINT `SATUAN_KERJA_SATKER_FAKULTAS_fkey` FOREIGN KEY (`SATKER_FAKULTAS`) REFERENCES `FAKULTAS`(`FAKULTAS_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
