-- AddForeignKey
ALTER TABLE `PRAJA` ADD CONSTRAINT `PRAJA_PRAJA_PROVINSI_fkey` FOREIGN KEY (`PRAJA_PROVINSI`) REFERENCES `PROVINSI`(`PROVINSI_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRAJA` ADD CONSTRAINT `PRAJA_PRAJA_ASAL_PENDAFTARAN_fkey` FOREIGN KEY (`PRAJA_ASAL_PENDAFTARAN`) REFERENCES `PROVINSI`(`PROVINSI_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
