-- AddForeignKey
ALTER TABLE `PRAJA` ADD CONSTRAINT `PRAJA_PRAJA_LOKASI_KAMPUS_fkey` FOREIGN KEY (`PRAJA_LOKASI_KAMPUS`) REFERENCES `LOKASI_KAMPUS`(`LOKASI_ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRAJA` ADD CONSTRAINT `PRAJA_PRAJA_LOKASI_KAMPUS_MUDA_fkey` FOREIGN KEY (`PRAJA_LOKASI_KAMPUS_MUDA`) REFERENCES `LOKASI_KAMPUS`(`LOKASI_ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRAJA` ADD CONSTRAINT `PRAJA_PRAJA_LOKASI_KAMPUS_MADYA_fkey` FOREIGN KEY (`PRAJA_LOKASI_KAMPUS_MADYA`) REFERENCES `LOKASI_KAMPUS`(`LOKASI_ID`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRAJA` ADD CONSTRAINT `PRAJA_PRAJA_LOKASI_KAMPUS_WASANA_fkey` FOREIGN KEY (`PRAJA_LOKASI_KAMPUS_WASANA`) REFERENCES `LOKASI_KAMPUS`(`LOKASI_ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
