-- CreateTable
CREATE TABLE `KELAS` (
    `KELAS_ID` VARCHAR(36) NOT NULL,
    `KELAS_NAMA` VARCHAR(200) NOT NULL,
    `KELAS_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `KELAS_UPDATED_AT` DATETIME(3) NULL,
    `KELAS_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`KELAS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
