-- AddForeignKey
ALTER TABLE `KELURAHAN` ADD CONSTRAINT `KELURAHAN_KELURAHAN_KECAMATAN_fkey` FOREIGN KEY (`KELURAHAN_KECAMATAN`) REFERENCES `KECAMATAN`(`KECAMATAN_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
