-- CreateTable
CREATE TABLE `FAKULTAS` (
    `FAKULTAS_ID` VARCHAR(36) NOT NULL,
    `FAKULTAS_NAMA` VARCHAR(200) NOT NULL,
    `FAKULTAS_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `FAKULTAS_UPDATED_AT` DATETIME(3) NULL,
    `FAKULTAS_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`FAKULTAS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
