-- CreateTable
CREATE TABLE `AGAMA` (
    `AGAMA_ID` VARCHAR(36) NOT NULL,
    `AGAMA_NAMA` VARCHAR(200) NOT NULL,
    `AGAMA_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `AGAMA_UPDATED_AT` DATETIME(3) NULL,
    `AGAMA_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`AGAMA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
