-- AddForeignKey
ALTER TABLE `AKSES_APLIKASI` ADD CONSTRAINT `AKSES_APLIKASI_AKSES_PENGGUNA_fkey` FOREIGN KEY (`AKSES_PENGGUNA`) REFERENCES `PENGGUNA`(`PENGGUNA_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
