-- CreateTable
CREATE TABLE `PROGRAM_STUDI` (
    `PRODI_ID` VARCHAR(36) NOT NULL,
    `PRODI_FAKULTAS` VARCHAR(36) NOT NULL,
    `PRODI_NAMA` VARCHAR(200) NOT NULL,
    `PRODI_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `PRODI_UPDATED_AT` DATETIME(3) NULL,
    `PRODI_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`PRODI_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
