-- CreateTable
CREATE TABLE `SATUAN` (
    `SATUAN_ID` VARCHAR(36) NOT NULL,
    `SATUAN_NAMA` VARCHAR(200) NOT NULL,
    `SATUAN_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SATUAN_UPDATED_AT` DATETIME(3) NULL,
    `SATUAN_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`SATUAN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
