-- CreateTable
CREATE TABLE `BIRO` (
    `BIRO_ID` VARCHAR(36) NOT NULL,
    `BIRO_NAMA` VARCHAR(200) NOT NULL,
    `BIRO_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `BIRO_UPDATED_AT` DATETIME(3) NOT NULL,
    `BIRO_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`BIRO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
