-- CreateTable
CREATE TABLE `LOGGER` (
    `LOG_ID` VARCHAR(36) NOT NULL,
    `LOG_PENGGUNA` VARCHAR(36) NOT NULL,
    `LOG_KEGIATAN` TEXT NOT NULL,
    `LOG_STATUS` BOOLEAN NOT NULL DEFAULT true,
    `LOG_KETERANGAN` TEXT NULL,
    `LOG_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`LOG_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
