-- CreateTable
CREATE TABLE `SATUAN_KERJA` (
    `SATKER_ID` VARCHAR(36) NOT NULL,
    `SATKER_LEMBAGA` VARCHAR(36) NULL,
    `SATKER_FAKULTAS` VARCHAR(36) NULL,
    `SATKER_BIRO` VARCHAR(36) NULL,
    `SATKER_SATUAN` VARCHAR(36) NULL,
    `SATKER_NAME` VARCHAR(200) NOT NULL,

    PRIMARY KEY (`SATKER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
