-- AddForeignKey
ALTER TABLE `LOKASI_APLIKASI` ADD CONSTRAINT `LOKASI_APLIKASI_LOKASI_SATUAN_KERJA_fkey` FOREIGN KEY (`LOKASI_SATUAN_KERJA`) REFERENCES `SATUAN_KERJA`(`SATKER_ID`) ON DELETE NO ACTION ON UPDATE CASCADE;
