-- CreateTable
CREATE TABLE `LOKASI_APLIKASI` (
    `LOKASI_ID` VARCHAR(36) NOT NULL,
    `LOKASI_APLIKASI` VARCHAR(36) NOT NULL,
    `LOKASI_SATUAN_KERJA` VARCHAR(36) NOT NULL,
    `LOKASI_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LOKASI_UPDATED_AT` DATETIME(3) NULL,

    PRIMARY KEY (`LOKASI_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
