-- CreateTable
CREATE TABLE `PENGGUNA` (
    `PENGGUNA_ID` VARCHAR(36) NOT NULL,
    `PENGGUNA_ROLE` VARCHAR(36) NOT NULL,
    `PENGGUNA_EMAIL` VARCHAR(150) NOT NULL,
    `PENGGUNA_USERNAME` VARCHAR(150) NOT NULL,
    `PENGGUNA_PASSWORD` VARCHAR(255) NOT NULL,
    `PENGGUNA_TOKEN` TEXT NULL,
    `PENGGUNA_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `PENGGUNA_UPDATED_AT` DATETIME(3) NULL,
    `PENGGUNA_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`PENGGUNA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
