-- AddForeignKey
ALTER TABLE `LOKASI_APLIKASI` ADD CONSTRAINT `LOKASI_APLIKASI_LOKASI_APLIKASI_fkey` FOREIGN KEY (`LOKASI_APLIKASI`) REFERENCES `APLIKASI`(`APLIKASI_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
