-- CreateTable
CREATE TABLE `PERAN` (
    `PERAN_ID` VARCHAR(36) NOT NULL,
    `PERAN_NAMA` VARCHAR(150) NOT NULL,
    `PERAN_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `PERAN_UPDATED_AT` DATETIME(3) NULL,
    `PERAN_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`PERAN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
