-- CreateTable
CREATE TABLE `ANGKATAN` (
    `ANGKATAN_ID` VARCHAR(36) NOT NULL,
    `ANGKATAN_NAMA` VARCHAR(200) NOT NULL,
    `ANGKATAN_CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ANGKATAN_UPDATED_AT` DATETIME(3) NULL,
    `ANGKATAN_IS_DELETED` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`ANGKATAN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
